version: '3'

services:
  db:
    image: postgres:13.4
    environment:
      POSTGRES_USER: over
      POSTGRES_PASSWORD: movie.1234
      POSTGRES_DB: movie
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  # backend:
  #   container_name: nestjs_api_dev
  #   build: .
  #   # command: yarn start:debug
  #   ports:
  #       - 8000:8000
  #   volumes:
  #       - ./src:/usr/src/app
  #       - /usr/src/app/node_modules
  #   environment:
  #     - DATABASE_HOST=db
  #     - DATABASE_PORT=${DATABASE_PORT}
  #     - DATABASE_USER=${DATABASE_USER}
  #     - DATABASE_PASSWORD=${DATABASE_PASSWORD}
  #     - DATABASE_NAME=${DATABASE_NAME}
  #     - DATABASE_SCHEMA=${DATABASE_SCHEMA}
  #     - DATABASE_SYNCHRONIZE=${DATABASE_SYNCHRONIZE}
  #     - JWT_SECRET=${JWT_SECRET}
  #     - AZURE_BLOB_CONNECTION_STRING=${AZURE_BLOB_CONNECTION_STRING}

  #   restart: unless-stopped

