version: '3'

services:
  db:
    image: postgres:13.4
    environment:
      POSTGRES_USER: over
      POSTGRES_PASSWORD: movie.1234
      POSTGRES_DB: movie
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
